### ISSUE TITLE
getting-startet

### ISSUE THREAD

**Issue by Otto404** [Akinzekeel/BlazorGrid#39]
unfortunately I have a few problems getting the software to fly.
As stated in https://blazorgrid.z6.web.core.windows.net/getting-started
I wrote 
```
using BlazorGrid.Providers;
...
builder.Services.AddBlazorGrid<DefaultHttpProvider>();
```

but there is no namespace provider in Blazorgrid. and

I can't find 
`AddBlazorGrid<type>`
 in the software either.

**Comment by Akinzekeel** [comment]
Thanks for getting in touch - and sorry it took me so long to get back to you. Flooding had knocked me off the grid for a while.

The Provider pattern is from an older version where you would need a class to request data and feed it into the grid. However this has changed and the provider is now just a delegate (i.e. similar to the Virtualize ItemsProvider).

Please remove the using BlazorGrid.Providers statement. AddBlazorGrid is no longer generic, so change the line to:
`builder.Services.AddBlazorGrid();`

I will be updating the document over course of the next week.

**Comment by Otto404** [comment]
Thank you
