### ISSUE TITLE
EmployeeController Server Side 

### ISSUE THREAD

**Issue by afofanov** [Akinzekeel/BlazorGrid#43]
Is it possible to get copy of EmployeeController (on server side) that is used for all demo pages?

**Comment by Akinzekeel** [comment]
Hello, 

there is actually no backend and no controller for the demo application. To keep the demo simple, all data actually comes from a static employees.json file. Each provider request downloads the entire file (from the server or from cache) and then applies paging / sorting / filtering to it.

In a real application, you would probably want to do the paging and sorting in a controller action. Please take a look at https://github.com/Akinzekeel/BlazorGrid/blob/master/BlazorGrid.Demo/Providers/CustomProvider.cs for some inspiration on how to implement that.

Let me know if you have any further questions.

**Comment by Akinzekeel** [comment]
Please check the updated Getting Started page, it now contains the entire code for the WeatherForecast controller. You can easily adapt it for other scenarios.
